////
Howto:
- Write this document such that it helps people to migrate. Describe what they should do.
- Chronological order is not necessary.
- Choose the right top level chapter (java, js, other)
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

== About This Document

This document describes all relevant changes *from Eclipse Scout {scout-previous-version} to Eclipse Scout {scout-version}*. If existing code has to be migrated, instructions are provided here.

WARNING: {NotReleasedWarning}

== Obtaining the Latest Version

=== Scout Runtime for Java

Scout Runtime artifacts for Java are distributed using Maven Central:

* {maven-central-link} on _Maven Central_
* {mvnrepository-link} on _mvnrepository.com_

Usage example in the parent POM of your Scout application:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.eclipse.scout.rt</groupId>
    <artifactId>org.eclipse.scout.rt</artifactId>
    <version>{maven-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== Scout Runtime for JavaScript

Scout Runtime artifacts for JavaScript are distributed using npm:

* https://www.npmjs.com/package/@eclipse-scout/core[Scout Core Runtime]
* https://www.npmjs.com/search?q=%40eclipse-scout[All official Scout JavaScript packages]

Usage example in your package.json:

[source,json]
[subs="verbatim,attributes"]
----
{
  "name": "my-module",
  "version": "1.0.0",
  "devDependencies": {
    "@eclipse-scout/cli": "{node-version}",
    "@eclipse-scout/releng": "^25.1.0"
  },
  "dependencies": {
    "@eclipse-scout/core": "{node-version}",
    "jquery": "3.7.1"
  }
}
----

The pre-built Scout JavaScript assets are also available using a CDN (e.g. to be directly included in a html document):
https://www.jsdelivr.com/package/npm/@eclipse-scout/core?path=dist

=== IDE Tooling (Scout SDK)

Scout officially supports https://www.jetbrains.com/idea/[IntelliJ IDEA] and {scout-sdk-download-link}.

==== IntelliJ IDEA

You can download the Scout plugin for IntelliJ IDEA from the https://plugins.jetbrains.com/plugin/13393-eclipse-scout/[JetBrains Plugin Repository] or you can use the plugins client built into IntelliJ IDEA.
Please refer to the https://www.jetbrains.com/help/idea/managing-plugins.html[IntelliJ Help] on how to install and manage plugins.

==== Eclipse

You can download the complete Eclipse IDE with Scout SDK included here: +
{scout-sdk-download-link}

To install the Scout SDK into your existing Eclipse IDE, use this P2 update site: +
{scout-sdk-update-site}

// ----------------------------------------------------------------------------

== New Build & Runtime Requirements

Scout 25.1 requires at least the following:

* Build and runtime of Scout 25.1 require Java 21 (Java 17 support has been dropped).
* Furthermore, the build requires
** Maven >= 3.9.9
** Node: >= 22.12.0
** Pnpm: >= 9.15.0

=== Pnpm Settings Changes

Pnpm 9 changed the default of `link-workspace-packages` from false to true, see
https://github.com/pnpm/pnpm/releases/tag/v9.0.0

Scout uses snapshot ranges (>=25.1.0-snapshot <25.1.0) in the `package.json` files instead of the `workspace:` protocol to link workspace packages together.

If the flag is false, `pnpm install` or `pnpm update` downloads the dependencies instead of using the ones from the workspace.

So this flag needs to be true when having more than one npm package in the workspace that depend on each other. To do so, add the property `link-workspace-packages=true` to your `.npmrc` file in your workspace or user home directory. We also recommend to put `prefer-workspace-packages=false` to ensure workspace packages are always preferred even if there are newer versions in the remote repository.

== Build Changes

* The Maven coordinates of the `git-commit-id-plugin` changed from `pl.project13.maven:git-commit-id-plugin` to `io.github.git-commit-id:git-commit-id-maven-plugin`.
* The Maven coordinates of the `download-maven-plugin` changed from `com.googlecode.maven-download-plugin:download-maven-plugin` to `io.github.download-maven-plugin:download-maven-plugin`.
* The support for the outdated `org.apache.tomcat.maven:tomcat7-maven-plugin` has been dropped. If you still rely on this plugin, you have to specify the desired version in your own scripts.

[[jakarta-activation-and-mail-update]]
== New version for Jakarta Activation and Jakarta Mail

For these dependencies the versions have been updated to the Jakarta EE 10 version:

* Jakarta Activation 2.1
* Jakarta Mail 2.1

As the _groupId_ has been changed for these dependencies, exclusions for the older version _com.sun.activation:jakarta.activation_ (resp. _mail_) have been added for other dependencies which did depend on these (maven duplicate-finder should point them out).
Existing exclusions for _jakarta.activation:jakarta.activation-api_ and _org.eclipse.angus:angus-activation_ (resp. _mail_) should be removed for other dependencies (two new dependencies instead of one to differ between API and implementation).

Modules including dependencies to _com.sun.activation:jakarta.activation_ should instead use _org.eclipse.angus:angus-activation_ (same for _mail_) as dependency (which includes the API and implementation).
If your implementation references implementation classes the package name needs to be adjusted (implementation has been moved).

== ClientCallback renamed to UiCallback

`org.eclipse.scout.rt.client.ui.desktop.ClientCallback` has been renamed to `org.eclipse.scout.rt.client.ui.desktop.hybrid.uicallback.UiCallback`.

Furthermore, invoking TypeScript code from the client Java code has been simplified using `org.eclipse.scout.rt.client.ui.desktop.hybrid.uicallback.UiCallbacks`. See the xref:technical-guide:user-interface/ui-callback.adoc[UI Callback technical guide] for more details.

== LESS constant renamed

The LESS constant `@icon-error` for the xref:technical-guide:user-interface/icons.adoc[font icon] with the code point U+E001 was renamed to `@icon-exclamation-mark-circle` to align it with its corresponding Java and JavaScript constants.

_Migration:_
Search for references to the constant `@icon-error` in your own *.less files and replace it with `@icon-exclamation-mark-circle` where appropriate.

== Scout JS

=== FormField: use _computeEmpty instead of _updateEmpty

If a widget implements `_updateEmpty` it should now implement `_computeEmpty` instead.
This guarantees that a property change event is triggered and the render function called, if there is any.
